using System;
using System.Collections.Generic;
using System.Text;

namespace Ban3.Infrastructures.NativeLibs.Enums
{
    /// <summary>
    /// Specifies one or more system-defined constants, 
    /// combined with a bitwise OR operation, 
    /// that provide additional information about the driver's device. 
    /// These constants include the following:
    /// </summary>
    [Flags]
    public enum DEVICE_OBJECT_CHARACTERISTICS
    {
        /// <summary>
        /// Directs the I/O manager to generate a name for the device, 
        /// instead of the caller specifying a DeviceName when it calls this routine. 
        /// The I/O manager makes sure that the name is unique. 
        /// This characteristic is typically specified by a PnP bus driver to generate a name for a physical device object (PDO) for a child device on the same bus. 
        /// This characteristic is new starting with Microsoft Windows 2000 and Microsoft Windows 98.
        /// </summary>
        FILE_AUTOGENERATED_DEVICE_NAME,

        /// <summary>
        /// Indicates that the device object is part of a Plug and Play (PnP) stack. 
        /// This characteristic is required if a bus driver (or bus filter driver) registers WMI support for a device object that has not yet received the IRP_MN_START_DEVICE request. 
        /// FILE_CHARACTERISTIC_PNP_DEVICE is also required if a function or filter driver registers for WMI before attaching to its device stack.
        /// </summary>
        FILE_CHARACTERISTIC_PNP_DEVICE,

        /// <summary>
        /// Indicates that the device object is part of a Terminal Services device stack. 
        /// Drivers should not set this characteristic.
        /// </summary>
        FILE_CHARACTERISTIC_TS_DEVICE,

        /// <summary>
        /// Indicates that a Web-based Distributed Authoring and Versioning (WebDAV) file system is mounted on the device. 
        /// Drivers should not set this characteristic.
        /// </summary>
        FILE_CHARACTERISTIC_WEBDAV_DEVICE,

        /// <summary>
        /// Indicates that a file system is mounted on the device. Drivers should not set this characteristic.
        /// </summary>
        FILE_DEVICE_IS_MOUNTED,

        /// <summary>
        /// Directs the I/O manager to apply the security descriptor of the device object to relative opens and trailing file name opens for the device. 
        /// For more information, see the Controlling Device Namespace Access topic.
        /// </summary>
        FILE_DEVICE_SECURE_OPEN,

        /// <summary>
        /// Indicates that the device is a floppy disk device.
        /// </summary>
        FILE_FLOPPY_DISKETTE,

        /// <summary>
        /// Indicates that the device cannot be written to.
        /// </summary>
        FILE_READ_ONLY_DEVICE,

        /// <summary>
        /// Indicates that the device is remote.
        /// </summary>
        FILE_REMOTE_DEVICE,

        /// <summary>
        /// Indicates that the storage device supports removable media. 
        /// Notice that this characteristic indicates removable media, not a removable device. 
        /// For example, drivers for JAZ drive devices should specify this characteristic, 
        /// but drivers for PCMCIA flash disks should not.
        /// </summary>
        FILE_REMOVABLE_MEDIA,

        /// <summary>
        /// Indicates that the volume is virtual. Drivers should not set this characteristic.
        /// </summary>
        FILE_VIRTUAL_VOLUME,

        /// <summary>
        /// Indicates that the device supports write-once media. 
        /// Drivers do not set this member directly. 
        /// For more information about how to set device characteristics, 
        /// see the Specifying Device Characteristics topic.
        /// </summary>
        FILE_WRITE_ONCE_MEDIA,

        /// <summary>
        /// Indicates that the device is a Cluster Shared Volume (CSV).
        /// </summary>
        FILE_CHARACTERISTIC_CSV,

        /// <summary>
        /// The IO Manager normally performs a full security check for traverse access on every file open when the client is an app container. 
        /// Setting of this flag bypasses this enforced traverse access check if the client token already has traverse privileges.
        /// </summary>
        FILE_DEVICE_ALLOW_APPCONTAINER_TRAVERSAL,

        /// <summary>
        /// Indicates that the underlying stack considers the device portable. 
        /// This is used by the storage stack 
        /// and means that the device is not in the local machine container and is not on a fixed bus type.
        /// </summary>
        FILE_PORTABLE_DEVICE
    }
}
